export const SAVE_USER_INFO = 'AUTH/SAVE_USER_INFO';

export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_IN_SUCCESS = 'AUTH/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'AUTH/SIGN_IN_FAILED';

export const VALIDATE_TOKEN = 'AUTH/VALIDATE_TOKEN';
export const VALIDATE_TOKEN_SUCCESS = 'AUTH/VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILED = 'AUTH/VALIDATE_TOKEN_FAILED';