export const SAVE_COURSE = 'COURSE/SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'COURSE/SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAILED = 'COURSE/SAVE_COURSE_FAILED';

export const FETCH_ALL_COURSE = 'COURSE/FETCH_ALL_COURSE';
export const FETCH_ALL_COURSE_SUCCESS = 'COURSE/FETCH_ALL_COURSE_SUCCESS';
export const FETCH_ALL_COURSE_FAILED = 'COURSE/FETCH_ALL_COURSE_FAILED';

export const TAKE_COURSE = 'COURSE/TAKE_COURSE';
export const TAKE_COURSE_SUCCESS = 'COURSE/TAKE_COURSE_SUCCESS';
export const TAKE_COURSE_FAILED = 'COURSE/TAKE_COURSE_FAILED';

export const FETCH_USER_COURSE = 'COURSE/FETCH_USER_COURSE';
export const FETCH_USER_COURSE_SUCCESS = 'COURSE/FETCH_USER_COURSE_SUCCESS';
export const FETCH_USER_COURSE_FAILED = 'COURSE/FETCH_USER_COURSE_FAILED';

export const FETCH_TEACHER_COURSE = 'COURSE/FETCH_TEACHER_COURSE';
export const FETCH_TEACHER_COURSE_SUCCESS = 'COURSE/FETCH_TEACHER_COURSE_SUCCESS';
export const FETCH_TEACHER_COURSE_FAILED = 'COURSE/FETCH_TEACHER_COURSE_FAILED';