export const SAVE_USER = 'USER/SAVE_USER';
export const SAVE_USER_SUCCESS = 'USER/SAVE_USER_SUCCESS';
export const SAVE_USER_FAILED = 'USER/SAVE_USER_FAILED';

export const DELETE_USER = 'USER/DELETE_USER';
export const DELETE_USER_SUCCESS = 'USER/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'USER/DELETE_USER_FAILED';

export const FETCH_ALL_USER = 'USER/FETCH_ALL_USER';
export const FETCH_ALL_USER_SUCCESS = 'USER/FETCH_ALL_USER_SUCCESS';
export const FETCH_ALL_USER_FAILED = 'USER/FETCH_ALL_USER_FAILED';

export const UPDATE_USER = 'USER/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'USER/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'USER/UPDATE_USER_FAILED';


export const UPDATE_PASSWORD = 'USER/UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'USER/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'USER/UPDATE_PASSWORD_FAILED';