export const CREATE_QUESTION = 'COURSE/CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'COURSE/CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILED = 'COURSE/CREATE_QUESTION_FAILED';

export const FETCH_TEACHER_QUESTIONS = 'COURSE/FETCH_TEACHER_QUESTIONS';
export const FETCH_TEACHER_QUESTIONS_SUCCESS = 'COURSE/FETCH_TEACHER_QUESTIONS_SUCCESS';
export const FETCH_TEACHER_QUESTIONS_FAILED = 'COURSE/FETCH_TEACHER_QUESTIONS_FAILED';

export const FETCH_COURSES_QUESTIONS = 'COURSE/FETCH_COURSES_QUESTIONS';
export const FETCH_COURSES_QUESTIONS_SUCCESS = 'COURSE/FETCH_COURSES_QUESTIONS_SUCCESS';
export const FETCH_COURSES_QUESTIONS_FAILED = 'COURSE/FETCH_COURSES_QUESTIONS_FAILED';