export const CREATE_QUESTION = 'COURSE/CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'COURSE/CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILED = 'COURSE/CREATE_QUESTION_FAILED';